### ISSUE TITLE
Cookbook Version 1.1.0 Silently Fails To Render S3 Content

### ISSUE THREAD

**Issue by toddmichael** [poise/citadel#24]
Running into issue with version 1.1.0 of the cookbook.  Using a standard `file` resource similar to the example.  The cookbook will converge on my Test Kitchen node, but the file is empty.  I set the constraint to pull 1.0.2 instead of the latest (1.1.0) and everything again worked as expected.  

I also tested this with a `JSON.parse` to see if I could glean more information this way and indeed I received an error, instead of the silent fail/converge.  

```
       JSON::ParserError
       -----------------
       A JSON text must at least contain two octets!
```

Something appears broken, or at least different, with cookbook version 1.1.0.  Happy to provide more information if it helps.  Cheers.

**Comment by coderanger** [comment]
How are you passing the credentials?

**Comment by toddmichael** [comment]
Hey @coderanger, thanks for swift response (as usual). 

Credentials set via Citadel attributes in `.kitchen.yml`.

```
platforms:
  - name: centos-7.1
    run_list:
      - recipe[my_cook::default]
    attributes:
      citadel:
        access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
```
